### ISSUE TITLE
Sick CI : Cycle 3 epic

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-tooling#13]
In a rough priority order (e.g. having poetry makes adding dependencies easier)

* [x] Land poetry support for SDW components - https://github.com/freedomofpress/securedrop-builder/pull/467
* [ ] Use black+Ruff to lint and autoformat projects - https://github.com/freedomofpress/securedrop-tooling/issues/10, and remove plugins 
* [ ] Migrate CI to GitHub Actions
  * [x] https://github.com/freedomofpress/securedrop-tooling/issues/5
* [ ] Enable dependabot for poetry repos

**Comment by cfm** [comment]
I would propose #14 here, for the sake of streamlining chores.

**Comment by zenmonkeykstop** [comment]
As per @legoktm , one poetry PR (sd-client) left to land, then we can probably wait to see how monorepo proposal shakes out.

**Comment by eloquence** [comment]
Closing as stale/done.
